### ISSUE TITLE
可以一起build一下这个latex模版hh

### ISSUE THREAD

**Issue by anglee0323** [Astro-Lee/YNUthesis#1]

**Comment by Astro-Lee** [comment]
非常欢迎你能参与这个template的开发！你有什么想法都可以提出来哦。

**Comment by anglee0323** [comment]
哈哈，学长毕业了嘛

**Comment by Astro-Lee** [comment]
我已经毕业了, 不在云大了

**Comment by Astro-Lee** [comment]
![image](https://github.com/Astro-Lee/YNUthesis/assets/61745903/086e7b91-5f51-479e-af06-331f6436dd9c)
