### ISSUE TITLE
空白页没有页码和页眉

### ISSUE THREAD

**Issue by xmsnoopy** [Astro-Lee/YNUthesis#3]
您好，目前发现模板还存在下面几个问题，请帮忙修复一下！！
1、论文独创性部分和摘要之间缺少空白页
2、从摘要到目录这部分之间页眉没有弄好
3、所有空白页目前都没有页码和页眉
4、英文摘要那个abstract，需要罗马字体
5、目录那页左边摘要、致谢和参考文献、成果等文字和右边页码之间都没有省略号
6、每章首页没有页眉

**Comment by xmsnoopy** [comment]
目前只剩下 英文摘要那个abstract，罗马字体修改不生效，其他的都可以了

**Comment by Astro-Lee** [comment]
对于英文摘要abstract是黑体这个问题，我在写模板的时候就注意到了，现在还没想到合适的解决方案。解决这个问题最快捷的方法是用pdf编辑软件（如 Adobe Acrobat）对其进行修改。谢谢。

**Comment by Astro-Lee** [comment]
您提到的其他问题，学校教务处也没有明确答复。
