### ISSUE TITLE
英文摘要罗马格式问题解决了，使用正则

### ISSUE THREAD

**Issue by wangshanshan2** [Astro-Lee/YNUthesis#5]
\cs_new_protected:Npn \__YNU_chapter:n #1
{
  \__YNU_sanitize_chapter_title:n {#1}
  \group_begin:
    \ctexset { chapter / numbering = false }
    % 使用正则表达式匹配只包含英文字符的标题
    \regex_match:nnTF {^[A-Za-z]+$} {#1}
      {
        % 如果标题只包含英文字符，则将标题设置为罗马字体
        \chapter [ \l__YNU_tmpa_tl ] {\rmfamily #1}
      }
      {
        % 如果标题不只包含英文字符，则保持默认字体
        \chapter [ \l__YNU_tmpa_tl ] {#1}
      }
  \group_end:
  \__YNU_chapter_header:n {#1}
}

**Comment by Astro-Lee** [comment]
The latest version of the code is available. Thanks for your help.
@xmsnoopy (#3 )

**Comment by wangshanshan2** [comment]
公式间距太大了，上下不要有空行。



---原始邮件---
发件人: "Rui-Zhi Li ***@***.***&gt;
发送时间: 2024年2月23日(周五) 中午11:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Astro-Lee/YNUthesis] 英文摘要罗马格式问题解决了，使用正则 (Issue #5)




 
The latest version of the code is available. Thanks for your help.
 @xmsnoopy (#3 )
